import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const CONTRACTS = ['MyToken']
const root = join(dirname(fileURLToPath(import.meta.url)), "..")

for (const CONTRACT_NAME of CONTRACTS) {
  const artifactPath = join(root, `contracts/out/${CONTRACT_NAME}.sol/${CONTRACT_NAME}.json`)
  const outPath = join(root, `lib/abis/${CONTRACT_NAME}.ts`)

  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"))
  if (!artifact.abi) {
    console.error("No abi in artifact. Run: cd contracts && forge build")
    process.exit(1)
  }

  mkdirSync(dirname(outPath), { recursive: true })

  const body = `/* Auto-generated by scripts/export-abi.mjs */
export const ${CONTRACT_NAME}ABI = ${JSON.stringify(artifact.abi, null, 2)} as const
`


  writeFileSync(outPath, body)
  console.log("Wrote", outPath)
}